### PR TITLE
Introduced small bugfixes

### PR DESCRIPTION
**Pull request by svenboesiger**
Needed to introduce small bugfixes and additional packages in order to get it working.

### CODE REVIEW

**Comment by step21** [comment]
Thanks for this, especially the change to the rpc request. IIRC the second fix might not be necessary if you run it from ./stream.py is that possible?

**Comment by svenboesiger** [comment]
Hi there

I can’t answer your question at the moment, when we amended the bugfix, we were only concerned about the transferal of the data to mongodb.

**Comment by step21** [comment]
Just to clarify: I am not the original author as you seem to assume. I just use it for my own work, and also came across this problem.
Btw, did it ever happen to you that in "if prev_max_block + STEP <= _highestBlockMongo:" prev_max_block was somehow left undefined? I tried to let the analysis run on my desktop instead with exactly the same ubuntu setup, but there I got this error. (hard crash because of prev_max_block being undefined) The only thing I can think of that could differ between the installs is the monodb database, though in principle the script should set that up the same, no?

**Comment by svenboesiger** [comment]
Hoi Step21

I can confirm that I have not encountered your error. I ran the script on my Ubuntu 16.04 as well on a friends mac. I can’t see a difference why it should crash, as you’ve indicated.

Cheers…
… and a nice weekend
Sven

**Comment by step21** [comment]
Mmh, thanks for clarifying. Now on my laptop, I got the above error after all the blocks were scanned & synced with mongodb. Weird.

**Comment by mobilenator** [comment]
Sadly it seems like Alex Miller abandoned this project.
The hex(n) change is just necessary.
I made it run on Win10, parsing 250 blocks per second by parallelizing the requests.
The problem with the current version here is, that each request makes a new session + TCP Handshake (~1second/block).

**Comment by step21** [comment]
Yeah. Thanks for your contribution. Just to understand your code - you initialize the session at the start, so that you do not have to do that for every request, right? But other than that, is it really parallelizing?
I noticed that in my fork, the hex(n) is called already in run() when calling add_block. Not sure which is better, but at least it is not possible to call hex() again.

**Comment by mobilenator** [comment]
the hex(n) call is so fast that it doesnt matter.
Actually I am not familiar with pythons loops parallelization with libs like requests, but I had logs opened and the requests were always 10 logLines ahead of the response logs from the rpc client.

this would fit my 40ms request timing.

**Comment by step21** [comment]
Sure, I didn't mean because of performance, but if I run it on my existing database with that extra call, it results in a TypeError, as the result of hex() is a string. So if anything it would have to be  `hex(int(n))` or something like that.

**Comment by step21** [comment]
Re parallelization: As far as I know, there is no 'built-in' parallelization. Of course it's good/helpful to only open the session once, if possible. But for proper parallelization, you need to keep track of which requests have already been sent, and the requests library definitely doesn't do that. There are libs that help with parallelization (or to use another word - threading) but by default this is not done afaik.
As a possible intermediary solution, you could try asynchronous requests, which does many requests at once though you would still have to loop it and might not be much use if the results are just processed one by one. (http://docs.python-requests.org/en/v0.10.6/user/advanced/)

**Comment by alex-miller-0** [comment]
Just looking at this repo and seeing all the activity. I did indeed abandon this long ago, but I would be happy to transfer admin rights if someone wants to be the maintainer. Who would be the best person/people to add?

**Comment by step21** [comment]
Hi, thanks for checking back in. I would be happy to get admin rights / co-maintainership, though I have to add that right now I am not sure how much I would develop this, though at least maintaining it is fine. This is mainly because I have also been working/contributing to mythril (https://github.com/Consensys/mythril ) and so I am not sure to what degree I will work on this repo, although mythril is mostly security focused.

**Pull request merged**
